### ISSUE TITLE
require() of ES modules is not supported.

### ISSUE THREAD

**Issue by ilomon10** [wojtekmaj/react-datetime-picker#315]
I cant use this library on nextjs

it just show error:
```bash
error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/xxxx/project/node_modules/react-clock/node_modules/get-user-locale/dist/esm/index.js
require() of ES modules is not supported.
require() of /home/xxxx/project/node_modules/react-clock/node_modules/get-user-locale/dist/esm/index.js from /home/xxxx/project/node_modules/react-clock/dist/cjs/shared/hourFormatter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/xxxx/project/node_modules/react-clock/node_modules/get-user-locale/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/xxxx/project/node_modules/react-clock/dist/cjs/shared/hourFormatter.js:7:41)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM',
  page: '/manager/template/editor/[template_id]'
}

```

Issues tested:
https://github.com/wojtekmaj/react-datetime-picker/issues/143
https://github.com/wojtekmaj/react-datetime-picker/issues/64

env:
next `12.1.0`
react-datetime-picker `4.2.0`

**Comment by wojtekmaj** [comment]
Fixed with get-user-locale 2.2.1, apparently
