### ISSUE TITLE
Error in picker's dependencies when use with enzyme

### ISSUE THREAD

**Issue by needpower** [wojtekmaj/react-datetime-picker#82]
When use enzyme's `mount` with `DateTimePicker`:
```
mount ( <DateTimePicker {...props} />)
```

there is an error:
```
TypeError: Cannot set property 'font' of null
```

Top of a callstack:
```
at measureText (../node_modules/update-input-width/dist/index.js:42:16)
      at updateInputWidth (../node_modules/update-input-width/dist/index.js:62:15)
      at ref (../node_modules/react-datetime-picker/node_modules/react-date-picker/dist/DateInput/Input.js:99:42)
```
Please, let me know if you need additional info about this issue.
Thanks in advance!

**Comment by wojtekmaj** [comment]
Hi,
thanks for letting me know. Please see https://github.com/wojtekmaj/update-input-width/issues/2 for a workaround and tracking any changes to this piece of code. Thanks!
